import java.util.ArrayList;

public final class Filters {

	public static String[] monthStrings = new String[] { "january", "february", "march", "april", "may", "june", "july",
			"august", "september", "october", "november", "december", "jan", "feb", "mar", "apr", "may", "jun", "jul",
			"aug", "sep", "oct", "nov", "dec" };

	public static String[] dayStrings = new String[] { "monday", "tuesday", "wednesday", "thursday", "friday",
			"saturday", "sunday" };

	public static String[] commonStrings = new String[] { "the", "be", "to", "of", "and", "these", "a", "in", "that",
			"is", "have", "i", "it", "its", "for", "not", "on", "with", "he", "she", "his", "her", "as", "you", "do",
			"at", "or", "a", "an", "will", "their", "there", "by", "date", "how", "from", "et", "more", "are", "your",
			"am", "pm", "site", "why", "where", "our", "this", "about", "us", "if", "about", "find", "but", "out", "we",
			"all", "after", "before", "say", "new", "what", "over", "lol", "just", "being", "was", "has", "still",
			"who", "into", "me", "they", "go", "hi", "can", "my", "welcome", "something", "it", "there", "around",
			"used", "something", "some", "around", "so", "up", "every", "them", "same", "need", "such", "also", "were",
			"which", "between", "than", "when", "through", "could", "other", "made", "been", "very", "would", "since",
			"thus", "later", "much", "another", "although", "while", "usually", "make", "only", "good", "get", "even",
			"now", "must", "asked", "page", "wow", "here", "big", "small", "one", "two", "three", "four", "five",
			"next", "see", "over", "under", "take", "top", "bottom", "it", "well", "most", "no", "had", "him", "least",
			"day", "world", "read", "little", "big", "nice", "according", "speaker", "parking", "bring", "prepare",
			"during", "entire", "request", "boring", "fun" };

	public static String[] internetCommon = new String[] { "blog", "blogs", "comment", "comments", "click", "feedback",
			"account", "browser", "password", "video", "audio", "download", "facebook", "twitter", "google", "apple",
			"youtube", "wordpress", "pinterest", "drupal", "archives", "cookies", "search", "subscribe", "subscription",
			"terms", "privacy", "settings", "home", "mobile", "contact", "email", "rss", "share", "pics", "pictures",
			"image", "followers", "follow", "web", "log", "html", "css", "javascript", "app", "submit", "reply", "name",
			"sign", "watch", "account", "online", "navigation", "bar", "toolbar", "firefox", "chrome", "safari", "ie",
			"iexplorer", "instagram", "font", "text", "toggle", "about", "profile", "content", "toggle", "dropdown",
			"services", "live", "confirm", "button", "frequently", "query", "hello", "say", "yes", "social", "new"};

	public static String[] geographyStrings = new String[] { "new", "york", "london", "paris", "berlin", "munich",
			"frankfurt", "stockholm", "helinski", "oslo", "moscow", "beijing", "seoul", "pyongyang", "kyoto", "tokyo",
			"hong", "kong", "san", "francisco", "los", "angeles", "chicago", "dublin", "rome", "madrid", "warsaw",
			"kiev", "instanbul", "cairo", "tehran", "baghdad", "riyadh", "shanghai", "mumbai", "bombay", "dehli",
			"bangkok", "singapore", "taipei", "melborne", "sydney", "canberra", "vancouver", "ottawa", "montreal",
			"calgary", "mexico", "city", "rio", "buenos", "aires", "damascus", "usa", "united", "states", "america",
			"uk", "kingdom", "france", "germany", "italy", "spain", "russia", "poland", "sweden", "norway", "finland",
			"greece", "ukraine", "saudi", "arabia", "iran", "israel", "syria", "iraq", "india", "china", "japan",
			"taiwan", "thailand", "canada", "australia", "mexico", "indonesia", "california", "brazil", "africa",
			"egypt", "ireland", "portugal", "austria", "hungary", "romania", "turkey" };

	public static String[] frequentEnglish = new String[] {
			//TODO: see if this can be optimized
			"improve", "mention", "worry", "affect", "treat", "discover",
			"perform", "manage", "fly", "shake", "apply", "control", "head", "contain", "reveal", "maintain", "respond",
			"finish", "imagine", "avoid", "care", "visit", "establish", "form", "enjoy", "sound", "remove", "claim",
			"forget", "design", "hang", "prove", "study", "guess", "laugh", "check", "force", "discuss", "state", "act",
			"miss", "compare", "answer", "present", "name", "arrive", "fail", "lay", "wonder", "indicate", "recognize",
			"argue", "prepare", "determine", "identify", "accept", "occur", "lie", "protect", "save", "shoot", "rise",
			"share", "enter", "note", "reduce", "push", "plan", "drop", "focus", "represent", "fill", "throw", "fight",
			"deal", "seek", "increase", "involve", "close", "place", "realize", "listen", "point", "cause", "choose",
			"draw", "catch", "describe", "cover", "face", "teach", "eat", "produce", "base", "hit", "end", "support",
			"wear", "pick", "agree", "join", "receive", "thank", "break", "drive", "carry", "develop", "hope",
			"explain", "return", "pull", "decide", "report", "require", "sell", "pass", "raise", "suggest", "remain",
			"kill", "reach", "cut", "fall", "stay", "build", "expect", "send", "die", "serve", "wait", "buy", "appear",
			"consider", "love", "remember", "offer", "win", "walk", "open", "grow", "spend", "add", "allow", "read",
			"speak", "create", "stop", "follow", "watch", "understand", "lead", "change", "learn", "set", "continue",
			"include", "meet", "pay", "lose", "stand", "sit", "provide", "write", "must", "happen", "bring", "hold",
			"believe", "live", "like", "move", "run", "play", "hear", "show", "might", "start", "turn", "talk", "help",
			"seem", "begin", "let", "keep", "mean", "put", "leave", "become", "feel", "need", "ask", "try", "call",
			"should", "may", "work", "tell", "give", "find", "use", "look", "want", "could", "come", "see", "take",
			"think", "will", "know", "make", "would", "get", "can", "go", "say", "do", "have", "be", "instead", "best",
			"suddenly", "close", "tonight", "that", "rather", "indeed", "clearly", "ok", "PM", "forward", "pretty",
			"particularly", "hard", "exactly", "thus", "usually", "before", "recently", "no", "quickly", "certainly",
			"soon", "nearly", "simply", "quite", "either", "especially", "early", "better", "less", "finally",
			"sometimes", "else", "little", "perhaps", "course", "home", "probably", "actually", "maybe", "both",
			"enough", "already", "around", "together", "ago", "least", "once", "much", "later", "almost", "however",
			"ever", "yet", "often", "away", "long", "far", "all", "today", "always", "off", "right", "where", "again",
			"over", "about", "why", "on", "most", "really", "never", "when", "too", "as", "in", "still", "down",
			"there", "back", "even", "very", "only", "well", "here", "also", "more", "then", "how", "now", "just",
			"out", "so", "up", "Word", "whoever", "ours", "hers", "yours", "another", "mine", "plenty", "his",
			"ourselves", "lots", "anybody", "nobody", "no", "none", "whom", "somebody", "yourself", "everybody",
			"herself", "each", "other", "myself", "anyone", "itself", "everyone", "themselves", "someone", "everything",
			"himself", "anything", "nothing", "something", "us", "her", "one", "him", "me", "them", "who", "she", "we",
			"they", "he", "you", "I", "it", "faculty", "flow", "incident", "black", "representative", "sector",
			"witness", "abortion", "household", "resolution", "holiday", "tie", "rise", "core", "league", "route",
			"opening", "improvement", "beach", "dish", "vegetable", "welfare", "tip", "copy", "intervention", "pepper",
			"fashion", "seed", "travel", "volume", "winner", "cloud", "hero", "minister", "doubt", "tear", "reference",
			"English", "beer", "judgment", "struggle", "wing", "expectation", "fun", "stand", "check", "requirement",
			"era", "master", "pleasure", "bond", "opposition", "coverage", "nurse", "tank", "debt", "secret", "bedroom",
			"confidence", "perception", "telephone", "variable", "topic", "length", "tooth", "mirror", "appeal",
			"division", "regime", "producer", "row", "ocean", "hall", "host", "frame", "bowl", "landscape", "fee",
			"gender", "motion", "rating", "silence", "manner", "dad", "user", "relief", "governor", "combination",
			"branch", "address", "chain", "golf", "basketball", "surgery", "soil", "meat", "percentage", "politician",
			"snow", "circumstance", "guide", "estate", "capacity", "contribution", "cat", "pilot", "shirt", "chief",
			"airport", "zone", "contrast", "component", "extent", "sheet", "duty", "ad", "outcome", "file", "dress",
			"setting", "bottle", "nose", "root", "content", "stress", "emergency", "beauty", "museum", "cash", "chest",
			"earth", "notion", "muscle", "traffic", "hearing", "meal", "male", "accident", "crew", "profit", "investor",
			"loan", "visitor", "trend", "thinking", "e-mail", "train", "bridge", "difficulty", "package", "appearance",
			"county", "revenue", "ring", "being", "regulation", "limit", "dance", "analyst", "shadow", "conclusion",
			"fruit", "thanks", "desk", "union", "storm", "theme", "human", "breast", "jury", "code", "novel", "trail",
			"photograph", "advice", "aid", "teaching", "works", "minority", "balance", "cover", "sight", "breath",
			"half", "consequence", "proposal", "poll", "surprise", "temperature", "pocket", "commitment", "weather",
			"instrument", "mom", "meaning", "panel", "soul", "athlete", "enemy", "planet", "sugar", "farmer", "lunch",
			"reading", "lip", "software", "ticket", "fat", "metal", "importance", "salt", "engine", "lead", "pool",
			"fight", "instruction", "leaf", "fuel", "respect", "injury", "assessment", "desire", "rain", "literature",
			"danger", "session", "map", "theater", "abuse", "army", "chicken", "football", "expression", "start",
			"writing", "plate", "plastic", "damage", "neck", "application", "colleague", "lady", "studio", "exchange",
			"island", "bottom", "front", "progress", "device", "circle", "democracy", "search", "birth", "actor",
			"will", "cut", "supply", "tape", "flower", "knee", "exercise", "pair", "justice", "contact", "classroom",
			"finding", "photo", "tour", "medicine", "Internet", "visit", "key", "victory", "category", "hell", "bus",
			"learning", "mean", "voter", "wine", "average", "bone", "function", "drive", "neighbor", "clothes",
			"location", "smile", "focus", "mistake", "committee", "context", "grade", "shoe", "connection",
			"intelligence", "construction", "perspective", "suit", "reaction", "background", "quarter", "move", "wave",
			"youth", "influence", "speed", "document", "coffee", "editor", "review", "religion", "gift", "murder",
			"belief", "egg", "baseball", "chairman", "procedure", "affair", "comment", "Christmas", "failure", "aspect",
			"critic", "equipment", "claim", "competition", "border", "principle", "folk", "shop", "ear", "path",
			"technique", "living", "river", "faith", "lesson", "title", "identity", "while", "protection", "block",
			"sample", "guest", "basis", "pound", "leadership", "advantage", "understanding", "facility", "flight",
			"vehicle", "tool", "share", "text", "reporter", "demand", "guard", "prison", "target", "horse", "band",
			"strength", "apartment", "crowd", "contract", "Ms", "reader", "shape", "district", "presence", "middle",
			"increase", "farm", "club", "gold", "resident", "screen", "run", "communication", "sales", "village",
			"winter", "tradition", "survey", "mountain", "return", "truck", "wood", "distance", "sun", "boat", "ice",
			"lack", "spot", "park", "attempt", "driver", "university", "scale", "stone", "solution", "ship", "status",
			"vision", "element", "hole", "fan", "crisis", "date", "beginning", "battle", "department", "insurance",
			"possibility", "weekend", "afternoon", "feature", "brain", "camp", "argument", "spirit", "conflict",
			"press", "researcher", "investigation", "turn", "variety", "conversation", "client", "concept", "labor",
			"attitude", "object", "plane", "freedom", "sky", "hope", "track", "species", "income", "troop", "act",
			"neighborhood", "safety", "version", "corner", "credit", "opinion", "bird", "relation", "judge",
			"restaurant", "access", "reform", "Senate", "video", "forest", "participant", "option", "speech",
			"customer", "mission", "wind", "majority", "citizen", "debate", "vote", "dinner", "audience", "break",
			"account", "score", "attorney", "responsibility", "threat", "newspaper", "victim", "mouth", "capital",
			"agreement", "scientist", "painting", "budget", "shot", "consumer", "kitchen", "partner", "task",
			"collection", "garden", "finger", "discussion", "investment", "violence", "yard", "Mrs", "coach", "reality",
			"item", "cancer", "generation", "gas", "machine", "owner", "agent", "skin", "pattern", "purpose", "surface",
			"marriage", "fall", "heat", "bag", "cause", "soldier", "hotel", "magazine", "method", "detail", "stuff",
			"property", "bar", "dream", "sea", "institution", "shoulder", "fear", "challenge", "trouble", "writer",
			"edge", "past", "range", "adult", "style", "unit", "conference", "evening", "trip", "production",
			"candidate", "weight", "bit", "politics", "structure", "camera", "fish", "chair", "interview", "measure",
			"play", "pain", "base", "peace", "employee", "weapon", "direction", "charge", "statement", "impact",
			"theory", "talk", "ball", "management", "radio", "Democrat", "firm", "spring", "expert", "trial", "cell",
			"seat", "card", "memory", "science", "network", "help", "manager", "note", "rock", "set", "executive",
			"public", "leg", "environment", "example", "song", "truth", "strategy", "station", "gun", "knowledge",
			"one", "sort", "design", "authority", "stage", "crime", "operation", "professor", "sister", "skill",
			"glass", "section", "lawyer", "sex", "benefit", "analysis", "message", "bill", "standard", "feeling",
			"election", "deal", "trade", "training", "TV", "box", "television", "region", "attack", "degree", "loss",
			"growth", "character", "staff", "ability", "amount", "cup", "success", "disease", "meeting", "resource",
			"answer", "pressure", "quality", "individual", "list", "thought", "sign", "media", "fund", "dog", "size",
			"approach", "treatment", "career", "stock", "scene", "artist", "east", "article", "decade", "factor",
			"animal", "response", "language", "series", "concern", "race", "page", "movement", "sound", "store",
			"color", "nature", "agency", "blood", "author", "order", "bed", "second", "goal", "top", "performance",
			"behavior", "rest", "officer", "subject", "board", "sport", "west", "bank", "security", "defense", "future",
			"fire", "risk", "church", "hospital", "economy", "call", "population", "material", "campaign", "floor",
			"Congress", "husband", "south", "administration", "daughter", "rule", "choice", "condition", "letter",
			"term", "opportunity", "plant", "summer", "course", "period", "energy", "brother", "chance", "culture",
			"window", "evidence", "century", "look", "hair", "organization", "source", "tree", "Republican", "film",
			"attention", "type", "computer", "baby", "step", "technology", "support", "love", "north", "movie", "test",
			"news", "worker", "patient", "wall", "doctor", "product", "land", "piece", "practice", "picture", "data",
			"phone", "image", "street", "figure", "industry", "cost", "situation", "oil", "American", "court", "need",
			"table", "star", "activity", "project", "site", "couple", "center", "matter", "official", "event", "form",
			"ground", "space", "paper", "record", "player", "position", "director", "tax", "society", "season", "model",
			"action", "building", "value", "difference", "arm", "road", "town", "relationship", "view", "son",
			"decision", "report", "price", "mind", "police", "wife", "voice", "light", "leader", "show", "drug",
			"heart", "rate", "effort", "role", "development", "field", "care", "control", "class", "use", "effect",
			"experience", "death", "interest", "college", "plan", "nation", "sense", "market", "music", "process",
			"policy", "age", "boy", "foot", "education", "force", "teacher", "air", "moment", "food", "guy", "girl",
			"research", "reason", "morning", "change", "result", "party", "history", "war", "art", "person", "health",
			"door", "office", "level", "others", "face", "parent", "back", "information", "body", "kid", "idea",
			"minute", "team", "president", "name", "community", "city", "car", "law", "member", "end", "line", "game",
			"hour", "power", "father", "friend", "service", "house", "head", "kind", "side", "issue", "business",
			"word", "job", "eye", "book", "study", "right", "lot", "month", "fact", "story", "money", "area", "mother",
			"room", "water", "home", "point", "Mr", "night", "number", "government", "work", "question", "program",
			"system", "company", "week", "case", "place", "part", "hand", "problem", "country", "group", "student",
			"family", "state", "school", "world", "child", "life", "woman", "thing", "man", "day", "way", "people",
			"year", "time", "thousand", "hundred", "billion", "last", "first", "two", "one", "casual", "interior",
			"elegant", "diplomatic", "regulatory", "full-time", "judicial", "reluctant", "bold", "purple", "generous",
			"oral", "decent", "teenage", "evil", "conscious", "promising", "handsome", "nonprofit", "residential",
			"structural", "anxious", "precise", "identical", "mild", "invisible", "electrical", "delicate",
			"theoretical", "frozen", "pleasant", "technological", "meaningful", "exclusive", "behavioral", "horrible",
			"genuine", "profound", "mechanical", "endless", "driving", "convinced", "intelligent", "drunk", "outer",
			"weird", "closed", "indigenous", "virtual", "grateful", "retired", "peaceful", "chronic", "continuing",
			"welcome", "uncomfortable", "fiscal", "minimum", "random", "outdoor", "medium", "maximum", "written",
			"overwhelming", "unexpected", "inevitable", "strict", "plain", "legislative", "longtime", "unlike",
			"mainstream", "Korean", "monthly", "Hispanic", "deadly", "administrative", "occasional", "Roman",
			"reliable", "missing", "patient", "estimated", "classical", "retail", "suburban", "harsh", "evident", "net",
			"experimental", "secondary", "ethical", "pleased", "subtle", "bare", "bitter", "excited", "continuous",
			"acceptable", "superior", "magic", "fit", "related", "gentle", "homeless", "okay", "exact", "collective",
			"cognitive", "sacred", "dear", "colonial", "changing", "African-American", "concrete", "principal",
			"adequate", "everyday", "lovely", "widespread", "awful", "frequent", "continued", "subsequent", "moderate",
			"worried", "ugly", "impressive", "artistic", "distinct", "running", "firm", "gifted", "wise", "weekly",
			"civilian", "institutional", "dependent", "legitimate", "naked", "hungry", "dominant", "terrorist",
			"offensive", "absolute", "brilliant", "relative", "temporary", "orange", "romantic", "detailed", "eager",
			"downtown", "curious", "agricultural", "modest", "sufficient", "loud", "desperate", "controversial",
			"asleep", "sophisticated", "proposed", "organic", "helpful", "painful", "rapid", "incredible", "OK",
			"given", "wealthy", "closer", "efficient", "slight", "athletic", "ongoing", "scared", "vulnerable", "ill",
			"round", "pale", "Irish", "radical", "exciting", "mere", "vital", "steady", "elderly", "stable",
			"prominent", "comprehensive", "defensive", "dirty", "sudden", "confident", "external", "intellectual",
			"considerable", "loose", "extensive", "assistant", "unknown", "working", "ideal", "relevant", "diverse",
			"attractive", "advanced", "mutual", "surprising", "raw", "remote", "innocent", "tremendous", "friendly",
			"complicated", "square", "solar", "tight", "odd", "Olympic", "accurate", "chemical", "genetic", "blind",
			"remarkable", "strategic", "stupid", "literary", "electric", "broken", "constitutional", "unlikely", "lost",
			"bottom", "super", "universal", "Canadian", "Italian", "distant", "pregnant", "rough", "extraordinary",
			"classic", "developing", "minor", "valuable", "ultimate", "Islamic", "Muslim", "clinical", "armed",
			"alternative", "mad", "flat", "biological", "fast", "conventional", "substantial", "giant", "Palestinian",
			"honest", "Latin", "extreme", "aggressive", "elementary", "wooden", "reasonable", "sensitive", "apparent",
			"historic", "pink", "wet", "permanent", "pretty", "straight", "due", "junior", "inner", "nearby", "smooth",
			"fellow", "pure", "electronic", "crucial", "nervous", "capable", "constant", "so-called", "holy",
			"increasing", "psychological", "usual", "digital", "Asian", "still", "fat", "severe", "fundamental",
			"congressional", "competitive", "visible", "intense", "amazing", "practical", "numerous", "ordinary",
			"glad", "online", "Mexican", "racial", "grand", "consistent", "opposite", "joint", "formal", "Spanish",
			"double", "Arab", "leading", "mass", "immediate", "later", "silent", "violent", "visual", "remaining",
			"existing", "brief", "sad", "unable", "lucky", "excellent", "dramatic", "musical", "spiritual", "Israeli",
			"fun", "illegal", "weak", "technical", "living", "guilty", "live", "proper", "gay", "outside", "creative",
			"sharp", "unusual", "secret", "useful", "solid", "narrow", "rural", "massive", "liberal", "enormous",
			"increased", "proud", "limited", "vast", "tired", "upper", "careful", "criminal", "essential", "multiple",
			"contemporary", "terrible", "initial", "overall", "gray", "cheap", "busy", "surprised", "industrial",
			"mean", "separate", "rare", "smart", "conservative", "typical", "official", "equal", "used", "German",
			"golden", "ancient", "just", "crazy", "Jewish", "correct", "funny", "English", "standard", "brown", "slow",
			"long-term", "Catholic", "sick", "actual", "ethnic", "internal", "unique", "thick", "Japanese", "angry",
			"comfortable", "obvious", "like", "prime", "yellow", "expensive", "Iraqi", "regional", "empty", "thin",
			"Supreme", "emotional", "presidential", "alone", "married", "impossible", "scientific", "complex",
			"greatest", "favorite", "educational", "mental", "urban", "strange", "corporate", "sweet", "Russian", "dry",
			"northern", "domestic", "extra", "alive", "male", "tall", "clean", "primary", "eastern", "appropriate",
			"familiar", "famous", "fair", "daily", "direct", "historical", "following", "negative", "healthy",
			"academic", "United", "moral", "dangerous", "cool", "chief", "active", "complete", "aware", "quiet",
			"Indian", "growing", "wonderful", "broad", "native", "afraid", "female", "soft", "regular", "responsible",
			"French", "annual", "warm", "present", "additional", "tiny", "bright", "light", "quick", "average", "wild",
			"interested", "previous", "willing", "Christian", "independent", "European", "potential", "future",
			"Soviet", "supposed", "front", "Chinese", "normal", "sorry", "very", "African", "British", "nuclear",
			"involved", "perfect", "powerful", "basic", "original", "effective", "concerned", "critical", "global",
			"fresh", "southern", "successful", "professional", "key", "senior", "western", "rich", "interesting",
			"safe", "civil", "positive", "modern", "total", "commercial", "tough", "sexual", "heavy", "beautiful",
			"middle", "necessary", "specific", "individual", "deep", "far", "top", "particular", "wide", "cultural",
			"traditional", "popular", "huge", "nice", "green", "main", "final", "cold", "religious", "legal", "close",
			"entire", "various", "dark", "democratic", "blue", "financial", "environmental", "general", "physical",
			"left", "simple", "ready", "serious", "happy", "central", "dead", "hot", "similar", "significant",
			"natural", "poor", "common", "fine", "foreign", "past", "private", "wrong", "current", "medical", "single",
			"short", "likely", "available", "difficult", "red", "open", "personal", "certain", "recent", "clear",
			"easy", "special", "full", "international", "federal", "TRUE", "military", "free", "whole", "possible",
			"strong", "economic", "better", "major", "hard", "late", "local", "human", "able", "early", "low", "sure",
			"public", "only", "social", "right", "best", "real", "white", "bad", "political", "important", "little",
			"long", "black", "different", "young", "national", "large", "small", "American", "big", "great", "old",
			"high", "good", "new", "other", "amid", "response", "subject", "re", "favor", "concerning", "versus",
			"depending", "prior", "top", "ahead", "via", "unlike", "other", "vs", "regarding", "plus", "addition",
			"towards", "beside", "beneath", "below", "except", "due", "but", "next", "past", "until", "worth", "terms",
			"front", "instead", "down", "throughout", "rather", "inside", "onto", "above", "since", "outside", "beyond",
			"despite", "away", "than", "near", "upon", "per", "well", "because", "according", "up", "along", "behind",
			"including", "off", "toward", "across", "within", "such", "among", "around", "under", "before", "without",
			"during", "against", "out", "between", "over", "after", "through", "like", "into", "as", "about", "by",
			"from", "at", "on", "with", "for", "to", "in", "of", "there", "no", "matter", "neither", "latter", "either",
			"fewer", "enough", "little", "whatever", "less", "half", "whose", "former", "several", "both", "each",
			"most", "few", "such", "same", "own", "much", "another", "any", "those", "many", "more", "these", "some",
			"which", "all", "what", "that", "this", "till", "case", "provided", "in", "not", "whereas", "soon",
			"rather", "for", "far", "except", "now", "long", "unless", "once", "like", "nor", "even", "although",
			"before", "whether", "until", "since", "after", "though", "so", "where", "while", "because", "than", "when",
			"if", "as", "or", "but", "that", "and", "every", "no", "our", "its", "your", "my", "her", "their", "his",
			"a", "the", "meal", "plan", "research", "university", "professional", 
			"corporate", "executive", "the", "culture", "committee",
			"career", "contact", "officer", "office", "management", "network", "group", "llc", "capital", "university",
			"universities", "college", "fund", "foundation", "inc.", "corp", "professional", "employee", "font",
			"about", "medical", "location", "portfolio", "course", "suggestion", "book", "chapter", "association",
			"organization", "development", "law", "sports", "medicine", "copyright", "job", "briefing", "tip", "pharmaceutical", 
			"immunotherapies", "immunotherapy", "antibody", "antibodies", "greater", "institute", "fellowship", "american", 
			"engineering", "inc", "networking", "advising", "campus", "ceremonies", "upcoming", "visiting", "faq"};
}
